name: CI - Testes REST e GraphQL

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Instalar dependências
        run: npm install
      - name: Iniciar servidor REST (porta 3000)
        run: nohup node server.js &
      - name: Iniciar servidor GraphQL (porta 4000)
        run: nohup node graphql/server.js &
      - name: Esperar servidores subirem
        run: sleep 10
      - name: Verificar servidor REST
        run: |
          for i in {1..20}; do
            nc -z localhost 3000 && break
            sleep 1
          done

      - name: Verificar servidor GraphQL
        run: |
          for i in {1..20}; do
            nc -z localhost 4000 && break
            sleep 1
          done
      - name: Executar todos os testes
        run: npm test
